import { Product } from "./types";

export const products: Product[] = [
  // Fruits
  {
    id: "f1",
    name: "Organic Fuji Apples",
    category: "Fruits",
    price: 3.99,
    originalPrice: 5.49,
    unit: "per lb",
    image: "/images/fuji-apples-red-organic.jpg",
    description: "Crisp, sweet Fuji apples grown without pesticides. Perfect for snacking, baking, or adding to salads. Rich in fiber and vitamin C.",
    badges: ["Organic", "Sale"],
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    featured: true,
  },
  {
    id: "f2",
    name: "Fresh Strawberries",
    category: "Fruits",
    price: 4.49,
    unit: "16 oz",
    image: "/images/fresh-strawberries-basket.jpg",
    description: "Plump, juicy strawberries picked at peak ripeness. Bursting with sweetness and loaded with antioxidants.",
    badges: ["Fresh", "Popular"],
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    featured: true,
  },
  {
    id: "f3",
    name: "Ripe Bananas",
    category: "Fruits",
    price: 1.29,
    unit: "per bunch",
    image: "/images/ripe-yellow-bananas-bunch.jpg",
    description: "Perfectly ripe bananas, great for smoothies, baking, or a quick energy boost. A household staple.",
    badges: ["Fresh"],
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
  },
  {
    id: "f4",
    name: "Seedless Watermelon",
    category: "Fruits",
    price: 7.99,
    unit: "whole",
    image: "/images/seedless-watermelon-whole.jpg",
    description: "Sweet, refreshing seedless watermelon. Perfect for summer gatherings and staying hydrated.",
    badges: ["Fresh", "Popular"],
    rating: 4.6,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: "f5",
    name: "Organic Blueberries",
    category: "Fruits",
    price: 5.99,
    originalPrice: 7.49,
    unit: "pint",
    image: "/images/organic-blueberries-pint.jpg",
    description: "Plump organic blueberries packed with antioxidants. Great for breakfast bowls, smoothies, or snacking.",
    badges: ["Organic", "Sale"],
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    featured: true,
  },
  {
    id: "f6",
    name: "Navel Oranges",
    category: "Fruits",
    price: 4.99,
    unit: "3 lb bag",
    image: "/images/navel-oranges-bag.jpg",
    description: "Juicy, easy-to-peel navel oranges. Excellent source of vitamin C and natural sweetness.",
    badges: ["Fresh"],
    rating: 4.5,
    reviewCount: 91,
    inStock: true,
  },
  // Vegetables
  {
    id: "v1",
    name: "Baby Spinach",
    category: "Vegetables",
    price: 3.49,
    unit: "5 oz bag",
    image: "/images/baby-spinach-fresh-bag.jpg",
    description: "Tender baby spinach leaves, triple-washed and ready to eat. Perfect for salads, smoothies, and sautéing.",
    badges: ["Organic", "Fresh"],
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    featured: true,
  },
  {
    id: "v2",
    name: "Roma Tomatoes",
    category: "Vegetables",
    price: 2.99,
    unit: "per lb",
    image: "/images/roma-tomatoes-fresh-red.jpg",
    description: "Firm, flavorful Roma tomatoes ideal for sauces, salads, and cooking. Vine-ripened for maximum flavor.",
    badges: ["Fresh"],
    rating: 4.6,
    reviewCount: 78,
    inStock: true,
  },
  {
    id: "v3",
    name: "Organic Broccoli",
    category: "Vegetables",
    price: 2.49,
    unit: "head",
    image: "/images/organic-broccoli-head-green.jpg",
    description: "Fresh organic broccoli crowns, rich in vitamins K and C. Versatile for steaming, roasting, or stir-frying.",
    badges: ["Organic"],
    rating: 4.8,
    reviewCount: 95,
    inStock: true,
  },
  {
    id: "v4",
    name: "Sweet Bell Peppers",
    category: "Vegetables",
    price: 3.99,
    unit: "3-pack",
    image: "/images/colorful-bell-peppers-mixed.jpg",
    description: "Vibrant mix of red, yellow, and orange bell peppers. Sweet, crunchy, and packed with vitamin C.",
    badges: ["Fresh", "Popular"],
    rating: 4.7,
    reviewCount: 143,
    inStock: true,
    featured: true,
  },
  {
    id: "v5",
    name: "Russet Potatoes",
    category: "Vegetables",
    price: 4.49,
    unit: "5 lb bag",
    image: "/images/russet-potatoes-bag.jpg",
    description: "Classic russet potatoes, perfect for baking, mashing, or frying. A pantry essential.",
    badges: [],
    rating: 4.5,
    reviewCount: 187,
    inStock: true,
  },
  {
    id: "v6",
    name: "Organic Carrots",
    category: "Vegetables",
    price: 2.29,
    unit: "1 lb bag",
    image: "/images/organic-carrots-bunch.jpg",
    description: "Sweet, crunchy organic carrots. Great for snacking, roasting, or adding to soups and stews.",
    badges: ["Organic"],
    rating: 4.6,
    reviewCount: 64,
    inStock: true,
  },
  // Dairy
  {
    id: "d1",
    name: "Whole Milk",
    category: "Dairy",
    price: 3.79,
    unit: "1 gallon",
    image: "/images/whole-milk-gallon-jug.jpg",
    description: "Fresh whole milk from local farms. Creamy and nutritious, perfect for drinking, cooking, and baking.",
    badges: ["Fresh"],
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    featured: true,
  },
  {
    id: "d2",
    name: "Greek Yogurt",
    category: "Dairy",
    price: 5.49,
    unit: "32 oz",
    image: "/images/greek-yogurt-plain-container.jpg",
    description: "Thick, creamy plain Greek yogurt. High in protein and probiotics. Great for breakfast or as a cooking ingredient.",
    badges: ["Popular"],
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
  },
  {
    id: "d3",
    name: "Sharp Cheddar Cheese",
    category: "Dairy",
    price: 6.99,
    originalPrice: 8.49,
    unit: "16 oz block",
    image: "/images/sharp-cheddar-cheese-block.jpg",
    description: "Aged sharp cheddar with bold, tangy flavor. Perfect for sandwiches, snacking, and melting.",
    badges: ["Sale"],
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
  },
  {
    id: "d4",
    name: "Free-Range Eggs",
    category: "Dairy",
    price: 4.99,
    unit: "dozen",
    image: "/images/free-range-eggs-carton.jpg",
    description: "Farm-fresh free-range eggs from hens raised on pasture. Rich yolks and superior flavor.",
    badges: ["Fresh", "Organic"],
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    featured: true,
  },
  {
    id: "d5",
    name: "Unsalted Butter",
    category: "Dairy",
    price: 4.29,
    unit: "1 lb",
    image: "/images/unsalted-butter-sticks.jpg",
    description: "Creamy unsalted butter made from high-quality cream. Essential for baking and cooking.",
    badges: [],
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
  },
  // Bakery
  {
    id: "b1",
    name: "Sourdough Bread",
    category: "Bakery",
    price: 5.99,
    unit: "loaf",
    image: "/images/sourdough-bread-loaf-artisan.jpg",
    description: "Artisan sourdough with a crispy crust and chewy interior. Made with a 48-hour fermented starter.",
    badges: ["Fresh", "Popular"],
    rating: 4.9,
    reviewCount: 267,
    inStock: true,
    featured: true,
  },
  {
    id: "b2",
    name: "Blueberry Muffins",
    category: "Bakery",
    price: 4.99,
    unit: "4-pack",
    image: "/images/blueberry-muffins-fresh-baked.jpg",
    description: "Freshly baked blueberry muffins bursting with real blueberries. Moist, fluffy, and irresistible.",
    badges: ["Fresh", "New"],
    rating: 4.8,
    reviewCount: 93,
    inStock: true,
  },
  {
    id: "b3",
    name: "Whole Wheat Bagels",
    category: "Bakery",
    price: 3.99,
    unit: "6-pack",
    image: "/images/whole-wheat-bagels-pack.jpg",
    description: "Hearty whole wheat bagels with a chewy texture. Perfect for breakfast sandwiches or toasting.",
    badges: [],
    rating: 4.5,
    reviewCount: 71,
    inStock: true,
  },
  {
    id: "b4",
    name: "Croissants",
    category: "Bakery",
    price: 6.49,
    unit: "4-pack",
    image: "/images/butter-croissants-flaky-fresh.jpg",
    description: "Buttery, flaky croissants baked fresh daily. Layers of delicate pastry make these a morning treat.",
    badges: ["Fresh"],
    rating: 4.9,
    reviewCount: 184,
    inStock: true,
    featured: true,
  },
  // Beverages
  {
    id: "bv1",
    name: "Cold Brew Coffee",
    category: "Beverages",
    price: 4.99,
    unit: "32 oz",
    image: "/images/cold-brew-coffee-bottle.jpg",
    description: "Smooth, low-acid cold brew coffee steeped for 20 hours. Ready to drink or customize with milk and sweetener.",
    badges: ["Popular", "New"],
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    featured: true,
  },
  {
    id: "bv2",
    name: "Fresh Orange Juice",
    category: "Beverages",
    price: 5.49,
    unit: "52 oz",
    image: "/images/fresh-squeezed-orange-juice.jpg",
    description: "100% pure squeezed orange juice with no added sugar or preservatives. Bright, tangy, and refreshing.",
    badges: ["Fresh"],
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
  },
  {
    id: "bv3",
    name: "Sparkling Water Variety",
    category: "Beverages",
    price: 6.99,
    originalPrice: 8.99,
    unit: "12-pack",
    image: "/images/sparkling-water-cans-variety.jpg",
    description: "Assorted flavors of zero-calorie sparkling water. Crisp, refreshing, and naturally flavored.",
    badges: ["Sale"],
    rating: 4.6,
    reviewCount: 112,
    inStock: true,
  },
  {
    id: "bv4",
    name: "Green Tea",
    category: "Beverages",
    price: 3.99,
    unit: "20-count",
    image: "/images/green-tea-bags-box.jpg",
    description: "Premium Japanese green tea bags. Light, grassy flavor with natural antioxidants. Perfect hot or iced.",
    badges: ["Organic"],
    rating: 4.7,
    reviewCount: 87,
    inStock: true,
  },
  // Snacks
  {
    id: "s1",
    name: "Mixed Nuts",
    category: "Snacks",
    price: 8.99,
    unit: "16 oz",
    image: "/images/mixed-nuts-roasted-salted.jpg",
    description: "Premium blend of cashews, almonds, walnuts, and pecans. Lightly salted and dry-roasted for maximum flavor.",
    badges: ["Popular"],
    rating: 4.8,
    reviewCount: 203,
    inStock: true,
    featured: true,
  },
  {
    id: "s2",
    name: "Kettle Chips",
    category: "Snacks",
    price: 3.49,
    originalPrice: 4.49,
    unit: "8 oz bag",
    image: "/images/kettle-chips-sea-salt.jpg",
    description: "Thick-cut kettle-cooked potato chips with sea salt. Extra crunchy and satisfying.",
    badges: ["Sale"],
    rating: 4.6,
    reviewCount: 167,
    inStock: true,
  },
  {
    id: "s3",
    name: "Dark Chocolate Bar",
    category: "Snacks",
    price: 3.99,
    unit: "3.5 oz",
    image: "/images/dark-chocolate-bar-70-percent.jpg",
    description: "Rich 70% dark chocolate made from ethically sourced cacao. Smooth, intense, and satisfying.",
    badges: ["Organic", "New"],
    rating: 4.9,
    reviewCount: 134,
    inStock: true,
  },
  {
    id: "s4",
    name: "Granola Bars",
    category: "Snacks",
    price: 5.99,
    unit: "6-pack",
    image: "/images/granola-bars-oat-honey.jpg",
    description: "Wholesome oat and honey granola bars with dried cranberries. Perfect on-the-go snack.",
    badges: [],
    rating: 4.5,
    reviewCount: 89,
    inStock: true,
  },
  // Meat
  {
    id: "m1",
    name: "Chicken Breast",
    category: "Meat",
    price: 7.99,
    unit: "per lb",
    image: "/images/boneless-chicken-breast-fresh.jpg",
    description: "Boneless, skinless chicken breasts from free-range chickens. Lean, versatile, and perfect for grilling or baking.",
    badges: ["Fresh"],
    rating: 4.7,
    reviewCount: 178,
    inStock: true,
    featured: true,
  },
  {
    id: "m2",
    name: "Ground Beef 80/20",
    category: "Meat",
    price: 6.49,
    unit: "per lb",
    image: "/images/ground-beef-fresh-package.jpg",
    description: "Fresh 80/20 ground beef, ideal for burgers, meatballs, and tacos. Rich flavor from the perfect fat ratio.",
    badges: ["Fresh"],
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
  },
  // Frozen
  {
    id: "fr1",
    name: "Frozen Peas",
    category: "Frozen",
    price: 2.49,
    unit: "16 oz bag",
    image: "/images/frozen-green-peas-bag.jpg",
    description: "Sweet frozen peas flash-frozen at peak freshness. Retain all nutrients and flavor. Ready in minutes.",
    badges: [],
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: "fr2",
    name: "Frozen Berry Mix",
    category: "Frozen",
    price: 5.99,
    unit: "32 oz bag",
    image: "/images/frozen-mixed-berries-bag.jpg",
    description: "Blend of strawberries, blueberries, raspberries, and blackberries. Perfect for smoothies and baking.",
    badges: ["Popular"],
    rating: 4.8,
    reviewCount: 112,
    inStock: true,
  },
];

export const categories = [
  { name: "Fruits", icon: "🍎", color: "bg-red-50 border-red-200" },
  { name: "Vegetables", icon: "🥦", color: "bg-green-50 border-green-200" },
  { name: "Dairy", icon: "🥛", color: "bg-blue-50 border-blue-200" },
  { name: "Bakery", icon: "🍞", color: "bg-amber-50 border-amber-200" },
  { name: "Beverages", icon: "🧃", color: "bg-orange-50 border-orange-200" },
  { name: "Snacks", icon: "🍿", color: "bg-yellow-50 border-yellow-200" },
  { name: "Meat", icon: "🥩", color: "bg-rose-50 border-rose-200" },
  { name: "Frozen", icon: "❄️", color: "bg-sky-50 border-sky-200" },
] as const;

export const getFeaturedProducts = () => products.filter((p) => p.featured);
export const getProductById = (id: string) => products.find((p) => p.id === id);
export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);
export const getRelatedProducts = (productId: string, category: string) =>
  products.filter((p) => p.category === category && p.id !== productId).slice(0, 4);
